---
# Tasks for routing-public
- name: Routing-Public - Gather facts about my VPC
  local_action:
    module: ec2_vpc_net_facts
    region: "{{ aws_region }}"
    filters:
      "tag:Name": "{{ vpc_name }}"
  register: vpcdata

- name: Export VPC ID for future use
  debug:
   var: vpcdata.vpcs[0].id

- name: Routing-Public - Gather facts Internet Gateways
  local_action:
    module: ec2_vpc_igw_facts
    region: "{{ aws_region }}"
  register: igw_facts

- name: Export IGW ID for future use
  debug:
   var: igw_facts.internet_gateways[1].internet_gateway_id

- name: Routing-Public - Gather facts about public subnets
  local_action:
    module: ec2_vpc_subnet_facts
    region: "{{ aws_region }}"
    filters:
      vpc-id: "{{ vpcdata.vpcs[0].id }}"
      "tag:Name": "{{ item }}"
  with_items:
    - Public Subnet 2A
    - Public Subnet 2B
    - Public Subnet 2C
  register: public_subnet_facts

- set_fact:
    subnet_ids: "{{ public_subnet_facts.results|map(attribute='subnets.0.id')|list }}"

- name: Routing-Public - New routing table for public subnets
  local_action:
    module: ec2_vpc_route_table
    vpc_id: "{{ vpcdata.vpcs[0].id }}"
    region: "{{ aws_region }}"
    tags:
      Name: Public Route table
    subnets: "{{ public_subnet_facts.results|map(attribute='subnets.0.id')|list }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ igw_facts.internet_gateways[1].internet_gateway_id }}"
  register: public_route_table
