---
# tasks file for vpc-lc-ssh
- name: Lc-Ssh - Gather facts about my VPC
  local_action:
    module: ec2_vpc_net_facts
    region: "{{ aws_region }}"
    filters:
      "tag:Name": "{{ vpc_name }}"
  register: vpcdata

- name: Export VPC ID for future use
  debug:
   var: vpcdata.vpcs[0].id

- name: Lc-Ssh - Gather facts about Security Group
  local_action:
    module: ec2_group_facts
    region: "{{ aws_region }}"
    filters:
      vpc-id: "{{ vpcdata.vpcs[0].id }}"
      group-name: HTTP_Allow
  register: group_id

- name: Export Security Group by group_id
  debug:
   var: group_id.security_groups[0].group_id

- name: Lc-Ssh - New Launch Configuration for AMI w/ SSH Access
  local_action:
    module: ec2_lc
    state: present
    name: JumpHost_lc
    region: "{{ aws_region }}"
    image_id: "{{ ami_image }}"
    key_name: "{{ key_name }}"
    security_groups: "{{ group_id.security_groups[0].group_id }}"
    instance_type: "{{ instance_type }}"
    volumes:
    - device_name: /dev/xvda
      volume_size: 30
      device_type: gp2
      iops: 3000
      delete_on_termination: true
    assign_public_ip: yes
  register: ssh_launch_config
