---
# Tasks for setting up NAT Gateways
- name: Gateways - Gather facts about my VPC
  local_action:
    module: ec2_vpc_net_facts
    region: "{{ aws_region }}"
    filters:
      "tag:Name": "{{ vpc_name }}"
  register: vpcdata

- name: Export VPC ID for future use
  debug:
   var: vpcdata.vpcs[0].id

- name: Gateways - Gather facts Internet Gateways
  local_action:
    module: ec2_vpc_igw_facts
    region: "{{ aws_region }}"
  register: igw_facts

- name: Export IGW ID for future use
  debug:
   var: igw_facts.internet_gateways[0].internet_gateway_id

- name: Gateways - Gather facts about public subnet 2a
  local_action:
    module: ec2_vpc_subnet_facts
    region: "{{ aws_region }}"
    filters:
      vpc_id: "{{ vpcdata.vpcs[0].id }}"
      "tag:Name": Public Subnet 2A
  register: subnet_id_a

- name: Export Subnet ID for future use
  debug:
   var: subnet_id_a.subnets[0].id

- name: Gateways - NAT Gateway and new EIP 1 of 3 ***These take time***
  local_action:
    module: ec2_vpc_nat_gateway
    state: present
    subnet_id: "{{ subnet_id_a.subnets[0].id }}"
    wait: no
    region: "{{ aws_region }}"
    if_exist_do_not_create: true
  register: nat_gateway_2a

- name: Gateways - Gather facts about public subnet 2b
  local_action:
    module: ec2_vpc_subnet_facts
    region: "{{ aws_region }}"
    filters:
      vpc_id: "{{ vpcdata.vpcs[0].id }}"
      "tag:Name": Public Subnet 2B
  register: subnet_id_b

- name: Export Subnet ID for future use
  debug:
   var: subnet_id_b.subnets[0].id

- name: Gateways - NAT Gateway and new EIP 2 of 3 ***These take time***
  local_action:
    module: ec2_vpc_nat_gateway
    state: present
    subnet_id: "{{ subnet_id_b.subnets[0].id }}"
    wait: no
    region: "{{ aws_region }}"
    if_exist_do_not_create: true
  register: nat_gateway_2b

- name: Gateways - Gather facts about public subnet 2b
  local_action:
    module: ec2_vpc_subnet_facts
    region: "{{ aws_region }}"
    filters:
      vpc_id: "{{ vpcdata.vpcs[0].id }}"
      "tag:Name": Public Subnet 2C
  register: subnet_id_c

- name: Export Subnet ID for future use
  debug:
   var: subnet_id_c.subnets[0].id

- name: Gateways - NAT Gateway and new EIP 3 of 3 ***These take time***
  local_action:
    module: ec2_vpc_nat_gateway
    state: present
    subnet_id: "{{ subnet_id_c.subnets[0].id }}"
    wait: yes
    region: "{{ aws_region }}"
    if_exist_do_not_create: true
  register: nat_gateway_2c
