---
# Tasks for routing-private
- name: Routing-Private - Gather facts about my VPC
  local_action:
    module: ec2_vpc_net_facts
    region: "{{ aws_region }}"
    filters:
      "tag:Name": "{{ vpc_name }}"
  register: vpcdata

- name: Export VPC ID for future use
  debug:
   var: vpcdata.vpcs[0].id

- name: Routing-Private - Gather Facts about Public subnet 2a
  local_action:
    module: ec2_vpc_subnet_facts
    region: "{{ aws_region }}"
    filters:
      vpc_id: "{{ vpcdata.vpcs[0].id }}"
      "tag:Name": Public Subnet 2A
  register: public_subnet_2a

- name: Export Subnet ID for future use
  debug:
   var: public_subnet_2a.subnets[0].id

- name: Routing-Private - Gather Facts about Private subnet 2a
  local_action:
    module: ec2_vpc_subnet_facts
    region: "{{ aws_region }}"
    filters:
      vpc_id: "{{ vpcdata.vpcs[0].id }}"
      "tag:Name": Private Subnet 2A
  register: private_subnet_2a

- name: Export Subnet ID for future use
  debug:
   var: private_subnet_2a.subnets[0].id

- name: HammerRouting - Gather Facts about NAT gateway in 2A
 local_action:
   module: ec2_vpc_nat_gateway_facts
   region: "{{ aws_region}}"
   filters:
     subnet-id: "{{ public_subnet_2a.subnets[0].id }}"
     state: ['available']
 register: nat_gateway_2a

- name: Export NAT Gateway ID for future use
  debug:
   var: nat_gateway_2a.result[0].NatGatewayId


- name: Routing-Private - New routing table for private subnet 2A
  local_action:
    module: ec2_vpc_route_table
    vpc_id: "{{ vpcdata.vpcs[0].id }}"
    region: "{{ aws_region }}"
    tags:
      Name: Private Routing Table 2A
    subnets: "{{ private_subnet_2a.subnets[0].id }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ nat_gateway_2a.result[0].NatGatewayId }}"
  register: private_route_table_2a
