---
# Tasks for routing-private
- name: Routing-Private - Gather facts about my VPC
  local_action:
    module: ec2_vpc_net_facts
    region: "{{ aws_region }}"
    filters:
      "tag:Name": Infrastructure VPC
  register: vpcdata

- name: Export VPC ID for future use
  debug:
   var: vpcdata.vpcs[0].id

- name: Routing-Private - Gather Facts about Public subnet 2c
  local_action:
    module: ec2_vpc_subnet_facts
    region: "{{ aws_region }}"
    filters:
      vpc_id: "{{ vpcdata.vpcs[0].id }}"
      "tag:Name": Public Subnet 2C
  register: public_subnet_2c

- name: Export Subnet ID for future use
  debug:
   var: public_subnet_2c.subnets[0].id

- name: Routing-Private - Gather Facts about Private subnet 2c
  local_action:
    module: ec2_vpc_subnet_facts
    region: "{{ aws_region }}"
    filters:
      vpc_id: "{{ vpcdata.vpcs[0].id }}"
      "tag:Name": Private Subnet 2C
  register: private_subnet_2c

- name: Export Subnet ID for future use
  debug:
   var: private_subnet_2c.subnets[0].id

- name: Routing-Private - New routing table for private subnet 2C
  local_action:
    module: ec2_vpc_route_table
    vpc_id: "{{ vpcdata.vpcs[0].id }}"
    region: "{{ aws_region }}"
    tags:
      Name: Private Routing Table 2C
    subnets: "{{ private_subnet_2c.subnets[0].id }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ gateway_2c }}"
  register: private_route_table_2c
